apiVersion: v1
kind: Service
metadata:
  name: ${SVCNAME}
  namespace: ${NS}
  labels:
    app: ${SVCNAME}
    service: ${SVCNAME}
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    app: ${SVCNAME}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-${SVCNAME}
  namespace: ${NS}
  labels:
    account: ${SVCNAME}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SVCNAME}-v1
  namespace: ${NS}
  labels:
    app: ${SVCNAME}
    version: v1
spec:
  selector:
    matchLabels:
      app: ${SVCNAME}
      version: v1
  template:
    metadata:
      labels:
        app: ${SVCNAME}
        version: v1
    spec:
      serviceAccountName: sa-${SVCNAME}
      containers:
        - name: ${SVCNAME}
          image: ${IMAGE}
          imagePullPolicy: Always
          args:
            - '--http-listen-address=:8000' # address the http server in the container listens on
            - '--ep-duration=0' # the default latency used for handling requests to / (echo handler)
            - '--ep-errors=0' # the default percentage of errors injected when handling echo requests
            - '--ep-headers=0' # the default percentage of double headers injected when handling echo requests
            - '--observability-instrumenter=skywalking' # the instrumenter to use, valid values are zipkin, skywalking
            - '--skywalking-reporter-endpoint=${SKYWALKING_ENDPOINT}'
            - '--skywalking-sample-rate=${SKYWALKING_SAMPLE_RATE}' # When we originate client request, this is the sample rate we use.
          env:
            - name: SVCNAME
              value: ${SVCNAME}
          ports:
            - name: http
              containerPort: 8000
